### ISSUE TITLE
Todo list modification

### ISSUE THREAD

**Issue by sangeetha-murugesan-sda9** [sangeetha-murugesan-sda9/ToDolist_final#1]
- [x] Write as data in file

- [x] Read as data in from file

- [x] Modify readme.md

- [x] Add Screen shots

- [x] Unit testing for methods for created classes

- [x] Test methods clearly expressed and followed naming conversion
